[package]
name = "day9"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
queues = "1.1.0"
structopt = "0.3.25"

[features]
